In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd 


In [6]:
df=pd.read_csv("multiple_linear_regression_data.csv")
df.head()

,TV_Ad_Spend,Radio_Ad_Spend,Newspaper_Ad_Spend,Product_Price,Sales
0,118.616634,9.557232,64.919101,7.325677,16.074992
1,285.707149,97.279510,10.245717,28.910958,23.655664
2,222.278243,50.581617,17.839614,29.328580,18.799258
3,183.610960,78.742750,90.058310,33.684346,19.305905
4,55.245406,136.597139,61.430048,37.674110,16.662194


In [10]:
X= df.iloc[: , 0:4]
Y= df.iloc[ :, -1]

Y

0     16.074992
1     23.655664
2     18.799258
3     19.305905
4     16.662194
        ...    
95    15.022177
96    20.956823
97    17.401275
98    10.797087
99    14.404635
Name: Sales, Length: 100, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2,random_state=2)

In [14]:
X_train.shape

(80, 4)

In [15]:
X_test.shape

(20, 4)

In [17]:
lr= LinearRegression()

In [19]:
lr.fit(X_train, Y_train)

LinearRegression()

In [20]:
lr.coef_

array([ 0.05085439,  0.07184824,  0.04200698, -0.08406178])

In [21]:
lr.intercept_

np.float64(4.191569406980223)

In [22]:
lr.predict(X_test.iloc[0:4])

array([11.8681314 , 19.95699969, 16.78399916, 11.30341265])

## Building my own multiple regression 

In [65]:
class Meramulti:

    def __init__(self):

        self.intercept_= None
        self.slope_= None

    def fit(self, X_train, Y_train):

        np.insert(X_train,0,1,axis=1)

        b_value= np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(Y_train)

        self.intercept_= b_value[0]
        self.slope_= b_value[1: ]

        print(f"The regression line thus obtaines has a intercept of {self.intercept_} and slopes of {self.slope_}")
        

    def predict(self,X_test):

        y_pred= np.dot(X_test,self.slope_) + self.intercept_
        return y_pred

In [66]:
lrg= Meramulti()


In [67]:
lrg.fit(X_train, Y_train)

The regression line thus obtaines has a intercept of 4.191569406980208 and slopes of [ 0.05085439  0.07184824  0.04200698 -0.08406178]


In [68]:
lrg.predict(X_test.iloc[0:4].values)

array([11.8681314 , 19.95699969, 16.78399916, 11.30341265])